# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'untitled.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QTextBrowser, QWidget)
from constants import *
import pyqtgraph as pg

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 623)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(480, 20, 93, 28))
        self.N_numer = QLineEdit(self.centralwidget)
        self.N_numer.setObjectName(u"N_numer")
        self.N_numer.setGeometry(QRect(130, 20, 113, 22))
        self.N = QLabel(self.centralwidget)
        self.N.setObjectName(u"N")
        self.N.setGeometry(QRect(110, 20, 71, 21))
        self.Taboo_neighbours = QLabel(self.centralwidget)
        self.Taboo_neighbours.setObjectName(u"Taboo_neighbours")
        self.Taboo_neighbours.setGeometry(QRect(30, 50, 111, 16))
        self.surv_part = QLabel(self.centralwidget)
        self.surv_part.setObjectName(u"surv_part")
        self.surv_part.setGeometry(QRect(70, 80, 55, 16))
        self.mut_prob = QLabel(self.centralwidget)
        self.mut_prob.setObjectName(u"mut_prob")
        self.mut_prob.setGeometry(QRect(70, 110, 55, 16))
        self.M_PSO = QLabel(self.centralwidget)
        self.M_PSO.setObjectName(u"M_PSO")
        self.M_PSO.setGeometry(QRect(80, 140, 55, 16))
        self.M_taboo = QLabel(self.centralwidget)
        self.M_taboo.setObjectName(u"M_taboo")
        self.M_taboo.setGeometry(QRect(70, 170, 55, 16))
        self.M_start = QLabel(self.centralwidget)
        self.M_start.setObjectName(u"M_start")
        self.M_start.setGeometry(QRect(80, 200, 55, 16))
        self.m_species = QLabel(self.centralwidget)
        self.m_species.setObjectName(u"m_species")
        self.m_species.setGeometry(QRect(70, 230, 55, 16))
        self.max_iter = QLabel(self.centralwidget)
        self.max_iter.setObjectName(u"max_iter")
        self.max_iter.setGeometry(QRect(80, 260, 55, 16))
        self.taboo_neighbours_num = QLineEdit(self.centralwidget)
        self.taboo_neighbours_num.setObjectName(u"taboo_neighbours_num")
        self.taboo_neighbours_num.setGeometry(QRect(130, 50, 113, 22))
        self.surr_part_num = QLineEdit(self.centralwidget)
        self.surr_part_num.setObjectName(u"surr_part_num")
        self.surr_part_num.setGeometry(QRect(130, 80, 113, 22))
        self.mut_prob_num = QLineEdit(self.centralwidget)
        self.mut_prob_num.setObjectName(u"mut_prob_num")
        self.mut_prob_num.setGeometry(QRect(130, 110, 113, 22))
        self.m_pso_num = QLineEdit(self.centralwidget)
        self.m_pso_num.setObjectName(u"m_pso_num")
        self.m_pso_num.setGeometry(QRect(130, 140, 113, 22))
        self.m_taboo_num = QLineEdit(self.centralwidget)
        self.m_taboo_num.setObjectName(u"m_taboo_num")
        self.m_taboo_num.setGeometry(QRect(130, 170, 113, 22))
        self.m_start_num = QLineEdit(self.centralwidget)
        self.m_start_num.setObjectName(u"m_start_num")
        self.m_start_num.setGeometry(QRect(130, 200, 113, 22))
        self.m_species_num = QLineEdit(self.centralwidget)
        self.m_species_num.setObjectName(u"m_species_num")
        self.m_species_num.setGeometry(QRect(130, 230, 113, 22))
        self.max_iter_num = QLineEdit(self.centralwidget)
        self.max_iter_num.setObjectName(u"max_iter_num")
        self.max_iter_num.setGeometry(QRect(130, 260, 113, 22))
        self.textBrowser = QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName(u"textBrowser")
        # self.textBrowser.setGeometry(QRect(320, 60, 391, 491))
        self.textBrowser.setGeometry(QRect(300, 60, 421, 171))
        self.long_term_cost = QLabel(self.centralwidget)
        self.long_term_cost.setObjectName(u"long_term_cost")
        self.long_term_cost.setGeometry(QRect(28, 320, 87, 20))
        self.omega = QLabel(self.centralwidget)
        self.omega.setObjectName(u"omega")
        self.omega.setGeometry(QRect(80, 350, 55, 16))
        self.c_1 = QLabel(self.centralwidget)
        self.c_1.setObjectName(u"c_1")
        self.c_1.setGeometry(QRect(100, 380, 55, 16))
        self.c2 = QLabel(self.centralwidget)
        self.c2.setObjectName(u"c2")
        self.c2.setGeometry(QRect(100, 410, 55, 16))
        self.b1 = QLabel(self.centralwidget)
        self.b1.setObjectName(u"b1")
        self.b1.setGeometry(QRect(100, 440, 55, 16))
        self.b2 = QLabel(self.centralwidget)
        self.b2.setObjectName(u"b2")
        self.b2.setGeometry(QRect(100, 470, 55, 16))
        self.c1_ga_pso = QLabel(self.centralwidget)
        self.c1_ga_pso.setObjectName(u"c1_ga_pso")
        self.c1_ga_pso.setGeometry(QRect(54, 500, 60, 16))
        self.c_2_ga_pso = QLabel(self.centralwidget)
        self.c_2_ga_pso.setObjectName(u"c_2_ga_pso")
        self.c_2_ga_pso.setGeometry(QRect(54, 530, 60, 16))
        self.long_term_cost_num = QLineEdit(self.centralwidget)
        self.long_term_cost_num.setObjectName(u"long_term_cost_num")
        self.long_term_cost_num.setGeometry(QRect(130, 320, 113, 22))
        self.omega_num = QLineEdit(self.centralwidget)
        self.omega_num.setObjectName(u"omega_2")
        self.omega_num.setGeometry(QRect(130, 350, 113, 22))
        self.c1_num = QLineEdit(self.centralwidget)
        self.c1_num.setObjectName(u"c1")
        self.c1_num.setGeometry(QRect(130, 380, 113, 22))
        self.c2_num = QLineEdit(self.centralwidget)
        self.c2_num.setObjectName(u"c2_num")
        self.c2_num.setGeometry(QRect(130, 410, 113, 22))
        self.b1_num = QLineEdit(self.centralwidget)
        self.b1_num.setObjectName(u"b1_num")
        self.b1_num.setGeometry(QRect(130, 440, 113, 22))
        self.b2_num = QLineEdit(self.centralwidget)
        self.b2_num.setObjectName(u"b2_num")
        self.b2_num.setGeometry(QRect(130, 470, 113, 22))
        self.c1_ga_pso_num = QLineEdit(self.centralwidget)
        self.c1_ga_pso_num.setObjectName(u"c1_ga_pso_2")
        self.c1_ga_pso_num.setGeometry(QRect(130, 500, 113, 22))
        self.c2_ga_pso_num = QLineEdit(self.centralwidget)
        self.c2_ga_pso_num.setObjectName(u"c2_ga_pso_num")
        self.c2_ga_pso_num.setGeometry(QRect(130, 530, 113, 22))
        
        self.plotWidget = pg.PlotWidget(self.centralwidget, background="white")
        self.plotWidget.setObjectName("plotWidget")
        self.plotWidget.setGeometry(QRect(300, 240, 421, 311))
        
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 26))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"HYBRID METAHEURISTICS", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"START", None))
        self.N_numer.setText(QCoreApplication.translate("MainWindow", str(N), None))
        self.N.setText(QCoreApplication.translate("MainWindow", u"N ", None))
        self.Taboo_neighbours.setText(QCoreApplication.translate("MainWindow", u"Taboo_neighbours", None))
        self.surv_part.setText(QCoreApplication.translate("MainWindow", u"surv_part", None))
        self.mut_prob.setText(QCoreApplication.translate("MainWindow", u"mut_prob", None))
        self.M_PSO.setText(QCoreApplication.translate("MainWindow", u"M_PSO", None))
        self.M_taboo.setText(QCoreApplication.translate("MainWindow", u"M_Taboo", None))
        self.M_start.setText(QCoreApplication.translate("MainWindow", u"M_start", None))
        self.m_species.setText(QCoreApplication.translate("MainWindow", u"M_species", None))
        self.max_iter.setText(QCoreApplication.translate("MainWindow", u"max_iter", None))
        self.long_term_cost.setText(QCoreApplication.translate("MainWindow", u"long_term_const", None))
        self.omega.setText(QCoreApplication.translate("MainWindow", u"omega", None))
        self.c_1.setText(QCoreApplication.translate("MainWindow", u"c1", None))
        self.c2.setText(QCoreApplication.translate("MainWindow", u"c2", None))
        self.b1.setText(QCoreApplication.translate("MainWindow", u"b1", None))
        self.b2.setText(QCoreApplication.translate("MainWindow", u"b2", None))
        self.c1_ga_pso.setText(QCoreApplication.translate("MainWindow", u"c_1_ga_pso", None))
        self.c_2_ga_pso.setText(QCoreApplication.translate("MainWindow", u"c_2_ga_pso", None))
        
        self.taboo_neighbours_num.setText(QCoreApplication.translate("MainWindow", str(TABOO_NEIGHBORS), None))
        self.surr_part_num.setText(QCoreApplication.translate("MainWindow", str(SURV_PART), None))
        self.mut_prob_num.setText(QCoreApplication.translate("MainWindow", str(MUTATION_PROB), None))
        self.m_pso_num.setText(QCoreApplication.translate("MainWindow", str(M_PSO), None))
        self.m_taboo_num.setText(QCoreApplication.translate("MainWindow", str(M_TABOO), None))
        self.m_start_num.setText(QCoreApplication.translate("MainWindow", str(START), None))
        self.m_species_num.setText(QCoreApplication.translate("MainWindow", str(M_SPECIES), None))
        self.max_iter_num.setText(QCoreApplication.translate("MainWindow", str(MAX_ITER), None))
        self.long_term_cost_num.setText(QCoreApplication.translate("MainWindow", str(LONG_TERM_CONST), None))
        self.omega_num.setText(QCoreApplication.translate("MainWindow", str(OMEGA), None))
        self.c1_num.setText(QCoreApplication.translate("MainWindow", str(C_1), None))
        self.c2_num.setText(QCoreApplication.translate("MainWindow", str(C_2), None))
        self.b1_num.setText(QCoreApplication.translate("MainWindow", str(B1), None))
        self.b2_num.setText(QCoreApplication.translate("MainWindow", str(B2), None))
        self.c1_ga_pso_num.setText(QCoreApplication.translate("MainWindow", str(C_1_GA_PSO), None))
        self.c2_ga_pso_num.setText(QCoreApplication.translate("MainWindow", str(C_2_GA_PSO), None))
    # retranslateUi

